accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mysite/', include('mysite.urls')),
    path('pages/', include('pages.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:content_id>/', views.detail, name='detail'),
    path('company_info/', views.company_info_view, name='company_info_view'),
    path("comment/create/<int:content_id>/", views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('mainpages/', views.mainpages_view, name='mainpages_view'),
    path('pages/', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('mainpages/', views.mainpage, name='mainpage'),
    path('company/', views.company, name='company'),
    path('company_info/', views.company_info, name='company_info'),

    ]

accounts/models.py
from django.db import models

# Create your models here.

mysite/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class MainContent(models.Model):
    objects = None
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published')
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('content_detail', args=[self.id])


class CompanyInfo(models.Model):
    # 필드 정의
    objects = None
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='company_info/')


class MainPages(models.Model):
    objects = None
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='mainpage_images/')


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(MainContent, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

pages/models.py
from django.db import models


class CompanyInfo(models.Model):
    objects = None
    title = models.CharField(max_length=200, default='Default Title')
    content = models.TextField()
    image = models.ImageField(upload_to='company_info/')

    def __str__(self):
        return self.title


class MainPage(models.Model):
    title = models.CharField(max_length=200, default='Default Title')
    image = models.ImageField(upload_to='images/')
    text = models.TextField()

    def __str__(self):
        return self.title
# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from accounts.forms import SignupForm


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignupForm()  # GET 요청에 대한 폼 인스턴스 생성
    return render(request, 'accounts/signup.html', {'form': form})

mysite/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from . import models
from .models import MainPages
from .models import MainContent, Comment, CompanyInfo
from .form import CommentForm
from django.core.exceptions import PermissionDenied


def company_info_view(request):
    company_info = CompanyInfo.objects.first()  # 첫 번째 CompanyInfo 인스턴스를 가져옴
    return render(request, 'pages/company_info.html', {'company_info': company_info})


def mainpages_view(request):
    mainpages = MainPages.objects.first()  # 첫 번째 MainPages 인스턴스를 가져옴
    return render(request, 'pages/mainpages.html', {'mainpages': mainpages})


def index(request):
    content_list = models.MainContent.objects.order_by('-pub_date')
    context = {'content_list': content_list}
    return render(request, 'mysite/content_list.html', context)


def detail(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)
    context = {'content_list': content_list}
    return render(request, 'mysite/content_detail.html', context)


@login_required(login_url='accounts:login')
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('detail', content_id=comment.content_list.id)
    else:
        form = CommentForm(instance=comment)

    context = {'comment': comment, 'form': form}
    return render(request, 'mysite/comment_form.html', context)


@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    return redirect('detail', content_id=comment.content_list.id)


@login_required(login_url='accounts:login')
def comment_create(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.content_list = content_list
            comment.author = request.user
            comment.save()
            return redirect('detail', content_id=content_list.id)
    else:
        form = CommentForm()
        context = {'content_list': content_list, 'form': form}
        return render(request, 'mysite/content_detail.html', context)

pages/views.py
from django.shortcuts import render
from .models import CompanyInfo, MainPage


def mainpage(request):
    mainpage_data = MainPage.objects.first()  # 첫 번째 MainPage 인스턴스를 가져옴
    return render(request, 'pages/mainpages.html', {'mainpage': mainpage_data})


def company_info(request):
    info = CompanyInfo.objects.first()  # 첫 번째 CompanyInfo 인스턴스를 가져옴
    return render(request, 'pages/company_info.html', {'company_info': info})


def company(request):
    return render(request, 'content_list.html')

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

{% if from.errors %}
<p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
{% endif %}

<form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
</form>
<p>아직 회원이 아니신가요? <a href="{% url 'accounts:signup' %}">회원가입</a></p>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>

{% endblock %}

templates/base.html
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="author" content="" />
    <title>{% block title %}기본 제목{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    {% include "footer.html" %}
</body>

templates/footer.html
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>

templates/mysite/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h2> update comment</h2>
<section class="mb-5">
     <div class="card bg-light">
         <div class="card-body">
             <form method="post" class="mb-4" action="{% url 'comment_update' comment.id %}">
             {% csrf_token %}
             <textarea id="content" name="content" class="form-control" rows="3">{{ form.content.value }}</textarea>
                 <button type="submit" class="btn btn-primary">submit</button>
             </form>
         </div>
     </div>
</section>
{% endblock %}
{% include "footer.html" %}

templates/mysite/content_detail.html
{% extends 'base.html' %}
{% block content %}
<!-- 이미지 추가 -->
<div class="text-center">
    {% if content_list.image %}
        <img class="img-fluid rounded mb-4" src="{{ content_list.image.url }}" alt="{{ content_list.title }}">
    {% endif %}
</div>

<h2>{{ content_list.title }}</h2>
<div>
    {{ content_list.content }}
</div>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <!-- 댓글 작성 양식 -->
            <form method="post" class="mb-4" action="{% url 'comment_create' content_list.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3" placeholder="내용을 입력해주세요."></textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
            <!-- 댓글 목록 -->
            {% for comment in content_list.comment_set.all %}
            <div class="d-flex">
                <div class="ms-3">
                    <div class="fw-bold">{{ comment.author.username }} &nbsp {{ comment.create_date }}
                        {% if comment.create_date != comment.modify_date %}
                        (수정됨: {{ comment.modify_date }})
                        {% endif %}
                    </div>
                    {{ comment.content }}
                    {% if request.user == comment.author %}
                       <a href="{% url 'comment_update' comment.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                       <a href="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outline-secondary">삭제</a>
                    {% endif %}
                </div>
            </div>
            <br/>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}
{% include "footer.html" %}

templates/mysite/content_list.html
{% extends 'base.html' %}
{% block content %}

<!-- Page Content-->
<div class="container px-4 px-lg-5">
    {% if content_list %}
        {% for content in content_list %}
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7">
                    <!-- 이미지 -->
                    <img class="img-fluid rounded mb-4 mb-lg-0" src="{{ content.image.url }}" alt="{{ content.title }}" />
                </div>
                <div class="col-lg-5">
                    <!-- 제목 -->
                    <h1 class="font-weight-light">{{ content.title }}</h1>
                    <!-- 내용 요약 -->
                    <p>{{ content.content|truncatewords:30 }}</p>
                    <!-- Call to Action 버튼 -->
                    {% if content.title == "패션" %}
                        <a class="btn btn-primary" href="{% url 'detail' content.id %}">확인해보기!</a>
                    {% elif content.title == "쿠폰" %}
                        <a class="btn btn-primary" href="{% url 'detail' content.id %}">확인해보기!</a>
                    {% elif content.title == "여행" %}
                        <a class="btn btn-primary" href="{% url 'detail' content.id %}">확인해보기!</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>There are no contents available.</p>
    {% endif %}
</div>

{% endblock %}
{% include "footer.html" %}

templates/navbar.html
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">배달해모아</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/mysite/">메인페이지</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/mainpages/">회사소개</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/company_info/">배달해모아</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (logout)</a> </li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

templates/pages/company_info.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-4 px-lg-5">
    {% if company_info %}
        <h1>{{ company_info.title }}</h1>
        <img class="img-fluid rounded mb-4 mb-lg-0" src="{{ company_info.image.url }}" alt="{{ company_info.title }}" />
        <p>{{ company_info.content }}</p>
    {% else %}
        <p>회사 정보가 현재 없습니다.</p>
    {% endif %}
</div>
{% endblock %}
{% include "footer.html" %}

templates/pages/mainpages.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-4 px-lg-5">
    {% if mainpage %}
        <h1>{{ mainpage.title }}</h1>
        <img class="img-fluid rounded mb-4 mb-lg-0" src="{{ mainpage.image.url }}" alt="{{ mainpage.title }}" />
        <p>{{ mainpage.text }}</p>
    {% else %}
        <p>회사소개 정보가 현재 없습니다.</p>
    {% endif %}
</div>
{% endblock %}
{% include "footer.html" %}